trigger:
  - main

variables:
  - name: dockerRegistryServiceConnection
    value: 'edu-arc-service-connection'
  - name: containerRegistry
    value: 'lotliteappacr.azurecr.io'
  - name: backendImageName
    value: 'lotlite-backend-edu'
  - name: tag
    value: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Images to ACR
    jobs:
      - job: BuildAndPushJob
        displayName: Build and Push Server
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # 2. Build & Push Backend using Docker@2
          - task: Docker@2
            displayName: "Build and Push Backend (Server)"
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(backendImageName)
              command: 'buildAndPush'
              Dockerfile: 'server/Dockerfile'
              buildContext: 'server'
              tags: |
                $(tag)
                latest
