trigger:
  - main

variables:
  - name: dockerRegistryServiceConnection
    value: 'edu-arc-service-connection'
  - name: frontendImageName
    value: 'lotlite'
  - name: backendImageName
    value: 'lotlite-backend'
  - name: tag
    value: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Images to ACR
    jobs:
      - job: BuildAndPushJob
        displayName: Build and Push Client & Server
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # 1. Build & Push Frontend using Docker@2
          - task: Docker@2
            displayName: "Build and Push Frontend (Client)"
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(frontendImageName)
              command: 'buildAndPush'
              Dockerfile: 'client/Dockerfile'
              buildContext: 'client'
              tags: |
                $(tag)
                latest
              arguments: '--build-arg VITE_API_BASE_URL=$(VITE_API_BASE_URL)'

          # 2. Build & Push Backend using Docker@2
          - task: Docker@2
            displayName: "Build and Push Backend (Server)"
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(backendImageName)
              command: 'buildAndPush'
              Dockerfile: 'server/Dockerfile'
              buildContext: 'server'
              tags: |
                $(tag)
                latest
